package com.fsc.supplier_service.enums;

public enum Industry {
    INFORMATION_TECHNOLOGY,
    MANUFACTURING,
    HEALTHCARE,
    EDUCATION,
    FINANCE,
    BANKING,
    INSURANCE,
    RETAIL,
    E_COMMERCE,
    TELECOMMUNICATIONS,
    TRANSPORTATION,
    LOGISTICS,
    CONSTRUCTION,
    REAL_ESTATE,
    AUTOMOTIVE,
    PHARMACEUTICALS,
    AGRICULTURE,
    FOOD_AND_BEVERAGE,
    ENERGY,
    MEDIA_AND_ENTERTAINMENT,
    HOSPITALITY,
    TOURISM,
    GOVERNMENT,
    NON_PROFIT,
    OTHER
}
